name: salary-regression-ci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - mlflow>=2.14
      - pandas>=2.2
      - scikit-learn>=1.5
      - numpy>=1.26
      - matplotlib>=3.8
      - joblib>=1.3
      - dagshub>=0.3
