name: salary-regression-ci
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - pip:
      - mlflow==2.17.2
      - pandas==2.2
      - scikit-learn==1.5.2
      - numpy==1.26.4
      - matplotlib==3.9.2
      - joblib==1.4.2
