name: MLflow CI

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.11"
        auto-activate-base: true

    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        pip install --upgrade pip

        pip install \
          mlflow==2.17.2 \
          pandas \
          numpy \
          scikit-learn \
          matplotlib \
          seaborn \
          joblib \
          dagshub

    - name: Run Training with MLflow Project
      shell: bash -l {0}
      env:
        MLFLOW_TRACKING_URI: sqlite:///${{ github.workspace }}/mlflow.db
      run: |
        mlflow run ./MLProject

    - name: Debug MLflow Structure
      run: |
        echo "===== SEARCH MLmodel ====="
        find . -name MLmodel

        echo ""
        echo "===== SEARCH MODEL DIR ====="
        find . -type d -name model

        echo ""
        echo "===== RUN ID FILE ====="

        if [ -f MLProject/artifacts/run_id.txt ]; then
          cat MLProject/artifacts/run_id.txt
        fi

    - name: Get Run ID That Contains Model
      id: modelrun
      shell: bash -l {0}
      run: |

        MODEL_PATH=$(find . -name MLmodel | head -n 1)

        echo "MODEL_PATH=$MODEL_PATH"

        RUN_ID=$(echo "$MODEL_PATH" | sed -E 's#.*mlruns/[0-9]+/([a-z0-9]+)/artifacts/model/MLmodel#\1#')

        echo "RUN_ID=$RUN_ID"

        echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: salary-regression-artifacts
        path: |
          MLProject/artifacts/
          mlruns/
        retention-days: 30

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Model
      shell: bash -l {0}
      env:
        MLFLOW_TRACKING_URI: sqlite:///${{ github.workspace }}/mlflow.db
      run: |

        echo "MODEL RUN ID = ${{ steps.modelrun.outputs.RUN_ID }}"

        mlflow models build-docker \
          -m "runs:/${{ steps.modelrun.outputs.RUN_ID }}/model" \
          -n salary-regression-ci

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker Image
      run: |
        docker tag salary-regression-ci \
        ${{ secrets.DOCKERHUB_USERNAME }}/salary-regression-ci:latest

    - name: Push Docker Image
      run: |
        docker push \
        ${{ secrets.DOCKERHUB_USERNAME }}/salary-regression-ci:latest